name: Deploy Luma documentation

on:
  push:
    branches:
      - main
    paths:
      - "examples/requests/**"
      - "src/**"
      - "docs/**"
      - ".github/workflows/deploy-luma-docs.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Luma dependencies
        env:
          POETRY_VIRTUALENVS_CREATE: "false" # ðŸ‘ˆ disables Poetryâ€™s own venv
        run: poetry install --no-interaction --no-ansi

      - name: Deploy Luma documentation
        working-directory: docs
        env:
          LUMA_API_KEY: ${{ secrets.LUMA_API_KEY }}
        run: |
          luma deploy
